# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: true
bioc_required: true

apt_packages:
 - libnetcdf-dev
 - netcdf-bin
 - libopenbabel-dev
 - r-cran-igraph

r:
  - release
  - devel

r_github_packages:
  - thomasp85/patchwork
  - jasenfinch/binneR
  - jasenfinch/metabolyseR
  - jasenfinch/mzAnnotation
  - jasenfinch/MFassign
  - jasenfinch/profilePro
  - jasenfinch/metaboWorkflows
  - jasenfinch/hrm

after_success:
    - Rscript -e 'covr::codecov()'
    
notifications:
    email:
    on_success: change
    on_failure: change