# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: true
bioc_required: true

apt_packages:
 - libnetcdf-dev
 - netcdf-bin

r:
  - release
  - devel

bioc_packages:
  - mzR

r_github_packages:
  - jasenfinch/binneR
  - jasenfinch/binneRlyse
  - jasenfinch/metabolyseR
  - aberhrml/FIEmspro

notifications:
    email:
    on_success: change
    on_failure: change