# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: true
bioc_required: true

apt_packages:
 - libnetcdf-dev
 - netcdf-bin
 - libopenbabel-dev

r:
  - release
  - devel

bioc_packages:
  - mzR

r_github_packages:
  - jasenfinch/binneR
  - aberhrml/FIEmspro
  - jasenfinch/metabolyseR
  - jasenfinch/mzAnnotation
  - jasenfinch/MFassign
  - jasenfinch/profilePro
  - jasenfinch/metaboData
  - jasenfinch/metaboWorkflows

notifications:
    email:
    on_success: change
    on_failure: change