---
title: "metaboReports"
subtitle: "`r paste0('v',packageVersion('metaboReports'))`"
author: "Jasen Finch"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  prettydoc::html_pretty:
    toc: true
    highlight: github
    theme: tactile
vignette: >
  %\VignetteIndexEntry{metaboReports-usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
library(knitr)
library(magrittr)
library(tibble)
```

## Introduction

## Basic usage

First load the library:

```{r setup}
library(metaboReports)
```

The parameters for the report can be defined using the `reportParameters()` functionas follows:

```{r parameters}
rp <- reportParameters(title = 'A metabolomics analysis',
                       investigator = 'Steve French',
                       sessionInfo = TRUE,
                       toc = TRUE,
                       path = '.')
```

Report methods are available for:

```{r, echo=FALSE,eval=TRUE}
tibble(
  Package = c('binneR','profilePro','metabolyseR','MFassign','metaboWorkflows'),
  Class = c('Binalysis','MetaboProfile','Analysis','Assignment','Workflow')
) %>%
  kable()
```


```{r report}
report(analysis,rp)
```


