---
title: "Example Report"
output: html_document
---

```{r libraryLoad,include=FALSE}
hrm::hrmAttach()
library(tidyverse)
library(missForest)
library(knitr)
```

```{r loadData,echo=FALSE}
load('../data/exampleFIEworkflowResults.RData')
```

```{r results,echo=FALSE}
processingResults <- analysis %>% 
  resultsProcessing()

analysisResults <- analysis %>%
  resultsAnalysis()
QCparameters <- analysisResults %>% {.@parameters@preTreat$QC}
```

## Overview

Technique: `r analysis %>% resultsParameters() %>% .@workflow`

Processing: `r processingResults@binLog`

Number of samples: 

## Processing

### Parameters

```{r binParamters,echo=FALSE}
processingResults@binParameters
```

```{r chromatograms,echo=FALSE}
chromatograms <- processingResults@spectra %>%
  .$headers
```

```{r chromatogramPlot,echo=FALSE}
scans <- processingResults@binParameters@scans
chromatograms <- chromatograms %>%
  select(FileName,acquisitionNum,totIonCurrent,polarity) %>%
  split(.$polarity) %>%
  map(~{
    f <- .
    f %>% 
      split(.$FileName) %>%
      map(~{
        s <- .
        s$acquisitionNum <- 1:nrow(s)
        return(s)
      }) %>% bind_rows()
  }) %>% bind_rows() %>%
  group_by(polarity,acquisitionNum) %>%
  summarise(totIonCurrent = mean(totIonCurrent))
chromatograms$polarity[chromatograms$polarity == 0] <- 'Negative'
chromatograms$polarity[chromatograms$polarity == 1] <- 'Positive'
chromatograms %>%
  ggplot(aes(x = acquisitionNum,y = totIonCurrent)) +
  geom_line() +
  geom_vline(xintercept = min(scans),colour = 'red',linetype = 2) +
  geom_vline(xintercept = max(scans),colour = 'red',linetype = 2) +
  theme_bw() +
  facet_wrap(~polarity) +
  xlab('Scan') +
  ylab('Total Ion Current')
```

## Quality Control

```{r rawFeatures,echo=FALSE}
rawInfo <- processingResults %>%
  info()
rawDat <- processingResults %>% 
  binnedData() %>% 
  map(~{
    d <- .
    d %>%
      rowid_to_column(var = 'Sample') %>%
      gather('Feature','Intensity',-Sample)
  }) %>%
  bind_rows(.id = 'Mode')

negFeatures <- rawDat %>%
  filter(Mode == 'n')

posFeatures <- rawDat %>%
  filter(Mode == 'p')
```


```{r TIC,echo=FALSE}
TICdat <- rawDat %>%
  group_by(Mode,Sample) %>%
  summarise(TIC = sum(Intensity)) %>%
  bind_cols(bind_rows(rawInfo,rawInfo)) %>%
  select(-Sample) %>%
  mutate(batchBlock = batchBlock %>% factor())

TICmedian <- TICdat %>%
  group_by(Mode) %>%
  summarise(Median = median(TIC),Q1 = Median - IQR(TIC),Q3 = Median + IQR(TIC),LowerOut = Q1 - IQR(TIC) * 1.5,UpperOut = Q3 + IQR(TIC) * 1.5)
```

```{r TICplot,echo=FALSE}
ggplot(TICdat,aes(x = injOrder,y = TIC,colour = batchBlock)) +
  geom_hline(data = TICmedian,aes(yintercept = Median)) +
  geom_hline(data = TICmedian,aes(yintercept = Q1),linetype = 2) +
  geom_hline(data = TICmedian,aes(yintercept = Q3),linetype = 2) +
  geom_hline(data = TICmedian,aes(yintercept = LowerOut),linetype = 3) +
  geom_hline(data = TICmedian,aes(yintercept = UpperOut),linetype = 3) +
  geom_point() +
  theme_bw() +
  facet_wrap(~Mode) +
  xlab('Injection Order') +
  ylab('Total Ion Count') +
  guides(colour = guide_legend(title = 'Batch Block'))
```

```{r extractQCsamples,include=FALSE}
QCidx <- QCparameters %>% {.$occupancyFilter$QCidx}
QCclass <- QCparameters %>% {.$occupancyFilter$cls}
QCocc <- QCparameters %>% {.$occupancyFilter$occupancy} %>% eval()
RSDthresh <- QCparameters %>% {.$RSDfilter$RSDthresh} %>% eval()
QCinfo <- rawInfo %>%
  filter(.[,QCclass] == QCidx)
QCdat <- rawDat %>%
  filter(Sample %in% QCinfo$fileOrder)

getMissingFeatures <- function(features) {
  features %>%
  .$Intensity %>% 
  .[. == 0] %>%
  length() %>% 
  {./nrow(QCdat)} %>%
  {. * 100} %>% 
  round(2)
}

missingNegFeatures <- QCdat %>% filter(Mode == 'n') %>% getMissingFeatures() 
missingPosFeatures <- QCdat %>% filter(Mode == 'p') %>% getMissingFeatures()

occ <- QCdat %>%
  filter(Intensity > 0) %>%
  group_by(Mode,Feature) %>%
  summarise(Occupied = n())

nocc <- QCdat %>%
  filter(Intensity == 0) %>%
  group_by(Mode,Feature) %>%
  summarise(Unoccupied = n())

occ <- occ %>%
  full_join(nocc,by = c("Mode", "Feature"))
occ$Unoccupied[is.na(occ$Unoccupied)] <- 0
occ$Occupied[is.na(occ$Occupied)] <- 0
occ <- occ %>%
  mutate(Total = Occupied + Unoccupied,Occupancy = Occupied/Total)

modeOcc <- function(occ,mode){
  occ %>%
    filter(Mode == mode,Occupancy >= QCocc) %>%
    .$Feature %>%
    unique() %>%
    length()
}
negOcc <- modeOcc(occ,'n')
posOcc <- modeOcc(occ,'p')

RSDdat <- QCdat %>%
  left_join(select(occ,Mode,Feature,Occupancy),by = c("Mode", "Feature")) %>%
  filter(Occupancy > QCocc) %>%
  select(-Occupancy) %>%
  split(.$Mode) %>%
  map(~{
    d <- .
    sample <- d$Sample
    d <- d %>%
      select(-Mode) %>%
      spread(Feature,Intensity) %>%
      select(-Sample)
    d[d == 0] <- NA
    set.seed(1234)
    d %>%
      as.matrix() %>%
      missForest() %>%
      .$ximp %>%
      as_tibble() %>%
      rowid_to_column(var = 'Sample') %>%
      gather('Feature','Intensity',-Sample)
  }) %>%
  bind_rows(.id = 'Mode')

RSD <- RSDdat %>%
  group_by(Mode,Feature) %>%
  summarise(RSD = sd(Intensity)/mean(Intensity))

modeRSD <- function(RSD,mode){
  RSD %>%
    filter(Mode == mode) %>%
    .$RSD %>%
    median()
}
negRSD <- modeRSD(RSD,'n')
posRSD <- modeRSD(RSD,'p')

negRSDfeat <- RSD %>%
  filter(Mode == 'n',RSD <= RSDthresh) %>%
  nrow()
posRSDfeat <- RSD %>%
  filter(Mode == 'p',RSD <= RSDthresh) %>%
  nrow()

QCstats <- tibble(Mode = c('Negative','Positive'),
                  `Raw Features` = c(negFeatures %>% .$Feature %>% unique() %>% length(),
                                     posFeatures %>% .$Feature %>% unique() %>% length()),
                  `Missing Data (%)` = c(missingNegFeatures,missingPosFeatures),
                  `Features with occupancy >= 2/3` = c(negOcc,posOcc),
                  `Median RSD` = c(negRSD %>% round(2),posRSD %>% round(2)),
                  `Features with RSD <= 0.5` = c(negRSDfeat,posRSDfeat)
)

```

```{r,echo=FALSE}
kable(QCstats)
```

```{r RSD,echo=FALSE}
suppressMessages(analysis %>%
                   resultsAnalysis() %>%
                   plotRSD()
)
```

## Pre-treatment



