
objectName <- function(x){
  deparse(substitute(x))
}

objectTitle <- function(x){
  object_name <- deparse(substitute(x))
  glue(
    "
## {object_name}  
"
  )
} 

loadData <- function(x){
  object_name <- deparse(substitute(x))
  glue(
  "
```{{r loadData}}
{object_name} <- read_rds('{object_name}.rds')
```
"
  )
}

argumentNames <- function(...){
  as.character(match.call())
}

setMethod('reportHeader',signature = 'Report',
          function(x){
            toc_option <- x %>%
              toc() %>%
              tolower()
            glue(
"
---
title: {title(x)}
investigator: {investigator(x)}
date: {time(x)}
output: 
  {output(x)}:
    toc: {toc_option}
---
"
            )
          })

setMethod('reportOptions',signature = 'Report',
          function(x){
            glue(
"
```{{r setup,include = FALSE}}
knitr::opts_chunk$set(fig.align = 'center',
                      cache = {cache(x)},
                      echo = {echo(x)})
```
"
            )
          })

setMethod('sessionInformationSection',signature = 'Report',
          function(x){
            if (sessionInformation(x)) {
              si <- glue(
'
## Session Info

```{{r sessionInfo}}
sessionInfo()
```
'
              )
            } else {
              si <- ''
            }
            
            return(si)
          })

setMethod('reportFooter',signature = 'Report',
          function(x){
            package_version <- packageVersion('metaboReports') %>% as.character()
            url <- packageDescription('metaboReports')$URL
            
            glue(
"
-----------
Generated by [metaboReports]{url} v{package_version}
"
            )
          })