
objectName <- function(x){
  deparse(substitute(x))
}

sectionTitle <- function(x){
  object_name <- deparse(substitute(x))
  glue(
    "
## {object_name}  
"
  )
} 

loadData <- function(x){
  object_name <- deparse(substitute(x))
  glue(
  "
```{{r loadData}}
{object_name} <- read_rds('{object_name}.rds')
```
"
  )
}

argumentNames <- function(...){
  as.character(match.call())
}

setMethod('sessionInformationSection',signature = 'Report',
          function(x){
            if (sessionInformation(x)) {
              si <- glue(
'
## Session Info

```{{r sessionInfo}}
sessionInfo()
```
'
              )
            } else {
              si <- ''
            }
            
            return(si)
          })

setMethod('reportFooter',signature = 'Report',
          function(x){
            package_version <- packageVersion('metaboReports') %>% as.character()
            url <- packageDescription('metaboReports')$URL
            
            glue(
"
-----------
Generated by [metaboReports]{url} v{package_version}
"
            )
          })