#' @importFrom stringr str_remove_all

sanitiseArgumentNames <- function(x){
  argument_names <- list()
  
  if (str_detect(x,'`') | str_detect(x,' ')){
    argument_names$name <- str_remove_all(x,'`')
    argument_names$file_name <- argument_names$name %>%
      tolower() %>%
      str_replace_all(' ','_')
  } else {
    argument_names$name <- x
    argument_names$file_name <- x
  }
  
  argument_names$variable <- x
  
  return(argument_names)
}

objectName <- function(x){
  object_name <- list()
  
  object_name$name <- deparse(substitute(x))
  
  object_name$chunk <- object_name$name %>%
    tolower() %>%
    str_replace_all(' ','_')
  
  if (str_detect(object_name$name,' ')) {
    object_name$variable <- glue("`{object_name$name}`")
  } else {
    object_name$variable <- object_name$name
  }
  
  return(object_name)
}

objectTitle <- function(...){
  object_name <- objectName(...)
  glue(
    "
## {object_name$name}  
"
  )
} 

loadData <- function(...){
  object_name <- objectName(...)
  glue(
  "
```{{r {object_name$chunk}_load_data}}
{object_name$variable} <- readr::read_rds('data/{object_name$chunk}.rds')
```
"
  )
}

argumentNames <- function(...){
  as.character(match.call())
}

setMethod('reportHeader',signature = 'Report',
          function(x){
            toc_option <- x %>%
              toc() %>%
              tolower()
            glue(
"
---
title: {title(x)}
author: {investigator(x)}
date: {time(x)}
output: 
  {output(x)}:
    toc: {toc_option}
---
"
            )
          })

setMethod('reportOptions',signature = 'Report',
          function(x){
            glue(
"
```{{r setup,include = FALSE}}
knitr::opts_chunk$set(fig.align = 'center',
                      cache = {cache(x)},
                      echo = {echo(x)})
```
"
            )
          })

setMethod('sessionInformationSection',signature = 'Report',
          function(x){
            if (sessionInformation(x)) {
              si <- glue(
'
## Session Info

```{{r session_info}}
sessionInfo()
```
'
              )
            } else {
              si <- ''
            }
            
            return(si)
          })

setMethod('reportFooter',signature = 'Report',
          function(x){
            package_version <- packageVersion('metaboReports') %>% as.character()
            url <- packageDescription('metaboReports')$URL
            
            glue(
"
-----------
Generated by [metaboReports]({url}) v{package_version}
"
            )
          })

#' @importFrom stringr str_replace_all
#' @importFrom rstudioapi initializeProject isAvailable
#' @importFrom readr write_file write_rds
#' @importFrom purrr walk

setMethod('reportDirectory',signature = 'Report',
          function(x){
            
            message('Creating report directory')
            
            report_title <-  x %>%
              title() %>%
              str_replace_all(' ','_')
            
            report_path <- glue("{path(x)}/{report_title}")
            
            glue("{report_path}/data") %>%
            dir.create(recursive = TRUE)
            
            message('Saving report data')
            
            if (isAvailable()) {
              initializeProject(report_path) 
            }
            
            report_rmd <- reportRMD(x)
            
            write_file(report_rmd,glue("{report_path}/{report_title}.Rmd"))
            
            report_data <- reportData(x)
            
            report_data %>%
              names() %>%
              walk(~{
                file_name <- sanitiseArgumentNames(.x)
                write_rds(report_data[[.x]],glue("{report_path}/data/{file_name$file_name}.rds"))
              })
          })

