#' @importFrom utils packageVersion

reportFooter <- function(){
  str_c('
### Session Info

```{r sessionInfo}
sessionInfo()
```

-----------
Generated by [metaboReports](https://github.com/jasenfinch/metaboReports) v',packageVersion('metaboReports') %>% as.character(),sep = '')
}