#' Report chunks
#' @rdname Report-chunks
#' @description General report chunks
#' @param x S4 object of class Report
#' @export

setMethod('reportHeader',signature = 'Report',
          function(x){
            toc_option <- x %>%
              toc() %>%
              tolower()
            header <- glue(
              "
---
title: {title(x)}
author: {investigator(x)}
date: {creationDate(x)}
output: 
  {output(x)}:
    toc: {toc_option}
---
"
            )
            chunk(text_above = header)
          })

#' @rdname Report-chunks
#' @export
 
setMethod('reportOptions',signature = 'Report',
          function(x){
            chunk_code <- glue("knitr::opts_chunk$set(fig.align = 'center',cache = {cache(x)},echo = {echo(x)})") %>%
              parse_expr()
            
            chunk(!!chunk_code,
                  label = 'setup',
                  chunk_options = list(include = FALSE))
          })

#' @rdname Report-chunks
#' @export

setMethod('sessionInformationSection',signature = 'Report',
          function(x){
            if (sessionInformation(x)) {
              si <- chunk(sessionInfo(),
                          label = 'session_info',
                          text_above = '## Session Info')
            } else {
              si <- chunk()
            }
            
            return(si)
          })

#' @rdname Report-chunks
#' @export

setMethod('reportFooter',signature = 'Report',
          function(x){
            package_version <- packageVersion('metaboReports') %>% as.character()
            url <- packageDescription('metaboReports')$URL
            
            chunk(text_above =  glue(
              "-----------
               Generated by [metaboReports]({url}) v{package_version}"
            ))
          })
