#' @importFrom utils packageVersion

reportFooter <- function(sessionInfo = TRUE){
  
  if (isTRUE(sessionInfo)) {
    sess <- '
## Session Info

```{r sessionInfo}
sessionInfo()
```

    '
  } else {
    sess <- ''
  }
  str_c(sess,'
-----------
Generated by [metaboReports](https://github.com/jasenfinch/metaboReports) v',packageVersion('metaboReports') %>% as.character(),sep = '')
}